//direccion con su calle, numero, nombre de region y comuna
SELECT D.CALLE, D.NUMERO, D.REFERENCIA, C.NOMBRE_COMUNA, R.NOMBRE_REGION 
FROM DIRECCION D
INNER JOIN COMUNA C ON C.ID_COMUNA = D.ID_COMUNA
INNER JOIN REGION R ON R.ID_REGION = C.ID_REGION
WHERE D.ID_DIRECCION = 1

//remuneraciones del año 2024 agrupadas por persona
SELECT P.IDENTIFICADOR_NACIONAL, SUM(R.SUELDO_PAGADO) AS REMUNERACIONES_2024 FROM PERSONAL PE
INNER JOIN PERSONA P ON P.ID_PERSONA = PE.ID_PERSONA
INNER JOIN REMUNERACIONES R ON R.ID_PERSONA = P.ID_PERSONA
WHERE R.ID_ESCUELA = 1 AND R.AGNO = 2024
GROUP BY P.IDENTIFICADOR_NACIONAL

//costo en equipamiento de escuela id 1
SELECT SUM(E.COSTO_ADQUISICION) AS COSTO_EQUIPAMIENTO 
FROM EQUIPAMIENTO E
INNER JOIN TIPO_EQUIPAMIENTO TE ON TE.ID_TIPO_EQUIPAMIENTO = E.ID_TIPO_EQUIPAMIENTO
WHERE E.ID_ESCUELA = 1 AND E.ESTADO = 1 AND TE.ESTADO = 1
